import type { KeyManager } from '../durable-objects/KeyManager';
import type { SessionStore } from '../durable-objects/SessionStore';
import type { AuthorizationCodeStore } from '../durable-objects/AuthorizationCodeStore';
import type { RefreshTokenRotator } from '../durable-objects/RefreshTokenRotator';
import type { RateLimiterCounter } from '../durable-objects/RateLimiterCounter';
import type { PARRequestStore } from '../durable-objects/PARRequestStore';
import type { ChallengeStore } from '../durable-objects/ChallengeStore';
/**
 * Cloudflare Workers Environment Bindings
 *
 * Durable Object bindings use generic type parameters for RPC type safety.
 * Example: DurableObjectNamespace<SessionStore> enables stub.getSessionRpc()
 */
export interface Env {
  DB: D1Database;
  DB_PII: D1Database;
  AVATARS: R2Bucket;
  STATE_STORE: KVNamespace;
  NONCE_STORE: KVNamespace;
  CLIENTS_CACHE: KVNamespace;
  USER_CACHE?: KVNamespace;
  CONSENT_CACHE?: KVNamespace;
  INITIAL_ACCESS_TOKENS?: KVNamespace;
  AUTHRIM_CONFIG?: KVNamespace;
  JWKS_CACHE?: KVNamespace;
  MAGIC_LINKS?: KVNamespace;
  KV?: KVNamespace;
  SETTINGS?: KVNamespace;
  REBAC_CACHE?: KVNamespace;
  KEY_MANAGER: DurableObjectNamespace<KeyManager>;
  SESSION_STORE: DurableObjectNamespace<SessionStore>;
  AUTH_CODE_STORE: DurableObjectNamespace<AuthorizationCodeStore>;
  REFRESH_TOKEN_ROTATOR: DurableObjectNamespace<RefreshTokenRotator>;
  CHALLENGE_STORE: DurableObjectNamespace<ChallengeStore>;
  RATE_LIMITER: DurableObjectNamespace<RateLimiterCounter>;
  USER_CODE_RATE_LIMITER: DurableObjectNamespace;
  PAR_REQUEST_STORE: DurableObjectNamespace<PARRequestStore>;
  DPOP_JTI_STORE: DurableObjectNamespace;
  TOKEN_REVOCATION_STORE: DurableObjectNamespace;
  DEVICE_CODE_STORE: DurableObjectNamespace;
  CIBA_REQUEST_STORE: DurableObjectNamespace;
  VERSION_MANAGER: DurableObjectNamespace;
  SAML_REQUEST_STORE: DurableObjectNamespace;
  PERMISSION_CHANGE_HUB?: DurableObjectNamespace;
  ISSUER_URL: string;
  ALLOWED_ORIGINS?: string;
  TOKEN_EXPIRY: string;
  CODE_EXPIRY: string;
  STATE_EXPIRY: string;
  NONCE_EXPIRY: string;
  REFRESH_TOKEN_EXPIRY: string;
  REFRESH_TOKEN_ROTATION_ENABLED?: string;
  ALLOW_HTTP_REDIRECT?: string;
  MAX_CODES_PER_USER?: string;
  STATE_REQUIRED?: string;
  USERINFO_REQUIRE_OPENID_SCOPE?: string;
  AUTH_CODE_TTL?: string;
  AUTH_CODE_CLEANUP_INTERVAL?: string;
  AUTHRIM_CODE_SHARDS?: string;
  AUTHRIM_SESSION_SHARDS?: string;
  AUTHRIM_CHALLENGE_SHARDS?: string;
  AUTHRIM_REVOCATION_SHARDS?: string;
  REGION_SHARD_TOTAL_SHARDS?: string;
  REGION_SHARD_GENERATION?: string;
  REGION_SHARD_APAC_PERCENT?: string;
  REGION_SHARD_ENAM_PERCENT?: string;
  REGION_SHARD_WEUR_PERCENT?: string;
  REGION_SHARD_GROUPS_JSON?: string;
  OPEN_REGISTRATION?: string;
  PRIVATE_KEY_PEM?: string;
  PUBLIC_JWK_JSON?: string;
  KEY_ID?: string;
  PAIRWISE_SALT?: string;
  OTP_HMAC_SECRET?: string;
  KEY_MANAGER_SECRET?: string;
  ADMIN_API_SECRET?: string;
  RESEND_API_KEY?: string;
  EMAIL_FROM?: string;
  DEFAULT_REDIRECT_URL?: string;
  UI_URL?: string;
  TRUSTED_JWT_ISSUERS?: string;
  TRUSTED_DOMAINS?: string;
  CODE_VERSION_UUID?: string;
  DEPLOY_TIME_UTC?: string;
  VERSION_CHECK_ENABLED?: string;
  RATE_LIMIT_PROFILE?: string;
  RATE_LIMIT_DISABLED?: string;
  ENABLE_TEST_ENDPOINTS?: string;
  RBAC_ID_TOKEN_CLAIMS?: string;
  RBAC_ACCESS_TOKEN_CLAIMS?: string;
  RBAC_CACHE_TTL?: string;
  RBAC_CACHE_VERSION?: string;
  USER_CACHE_TTL?: string;
  CONSENT_CACHE_TTL?: string;
  CONFIG_CACHE_TTL?: string;
  RBAC_CONSENT_ORG_SELECTOR?: string;
  RBAC_CONSENT_ACTING_AS?: string;
  RBAC_CONSENT_SHOW_ROLES?: string;
  ENABLE_SD_JWT?: string;
  ENABLE_POLICY_EMBEDDING?: string;
  ENABLE_HTTPS_REQUEST_URI?: string;
  HTTPS_REQUEST_URI_ALLOWED_DOMAINS?: string;
  HTTPS_REQUEST_URI_TIMEOUT_MS?: string;
  HTTPS_REQUEST_URI_MAX_SIZE_BYTES?: string;
  ENABLE_TOKEN_EXCHANGE?: string;
  TOKEN_EXCHANGE_ALLOWED_TYPES?: string;
  TOKEN_EXCHANGE_MAX_RESOURCE_PARAMS?: string;
  TOKEN_EXCHANGE_MAX_AUDIENCE_PARAMS?: string;
  ENABLE_CLIENT_CREDENTIALS?: string;
  IDENTITY_STITCHING_ENABLED?: string;
  IDENTITY_STITCHING_REQUIRE_VERIFIED_EMAIL?: string;
  RP_TOKEN_ENCRYPTION_KEY?: string;
  EMAIL_DOMAIN_HASH_SECRET?: string;
  ENABLE_CUSTOM_CLAIMS?: string;
  ENABLE_ID_LEVEL_PERMISSIONS?: string;
  MAX_EMBEDDED_PERMISSIONS?: string;
  MAX_RESOURCE_PERMISSIONS?: string;
  MAX_CUSTOM_CLAIMS?: string;
  INTROSPECTION_STRICT_VALIDATION?: string;
  INTROSPECTION_EXPECTED_AUDIENCE?: string;
  INTROSPECTION_CACHE_ENABLED?: string;
  INTROSPECTION_CACHE_TTL_SECONDS?: string;
  ENVIRONMENT?: string;
  NODE_ENV?: string;
  SUPPORTED_ACR_VALUES?: string;
  ENABLE_CHECK_API?: string;
  CHECK_API_DEBUG_MODE?: string;
  CHECK_API_WEBSOCKET_ENABLED?: string;
  CHECK_API_AUDIT_ENABLED?: string;
  ENABLE_MOCK_AUTH?: string;
  CHECK_CACHE_KV?: KVNamespace;
  DEFAULT_TENANT_ID?: string;
}
//# sourceMappingURL=env.d.ts.map
